#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

REDIRECT_URL="https://docs.nginx.com/nginx/admin-guide/web-server/"
	
apt-get update
apt-get install -y nginx
ufw allow 'Ngnix HTTP'
sudo echo 'Hello World!' | tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $REDIRECT_URL 301;" /etc/nginx/sites-available/default
service nginx restart
