#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

REDIRECT_URL="https://docs.nginx.com/nginx/admin-guide/web-server/"
	
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Ngnix HTTP'
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        rewrite ^/redirect_me $REDIRECT_URL permanent;
    }
}" | sudo tee /etc/nginx/sites-available/temp-config
sudo ln -s /etc/nginx/sites-available/temp-config /etc/nginx/sites-enabled/
service nginx restart

