#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get install -y nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/index_404.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;


	root /var/www/html;
	index index.html index.htm;


	server_name _;


	error_page 404 /index_404.html;
	location = /index_404.html {
		internal;
	}

	location /redirect_me {
		return 301 https://docs.nginx.com/nginx/admin-guide/web-server/;
	}
}" | sudo tee /etc/nginx/sites-available/custom-config
sudo ln -s /etc/nginx/sites-available/custom-config /etc/nginx/sites-enabled/
sudo service nginx restart
