#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install -y nginx

echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   sever_name _;

   location / {
   add_header X-Served-By $HOSTNAME;
   root /var/www/html;
   index index.html
   }
}" | sudo tee /etc/nginx/sites-available/custom-config
sudo ln -s /etc/nginx/sites-available/custom-config /etc/nginx/sites-enabled/
sudo service nginx restart
