#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

sudo apt-get update
sudo apt-get install -y haproxy

echo "frontend  Mosesomo-frontend
	      bind *:80
	      mode http
	      default_backend Mosesomo-backend

      backend  Mosesomo-backend
             balance roundrobin
	     server 308145-web-01 52.3.252.97:80 check
	     server 308145-web-02 100.25.197.100:80 check" | sudo tee /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
